import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "./lenis-provider";
import { HeaderNav } from "./header-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background text-foreground">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider>
          <div className="relative flex min-h-screen flex-col">
            <header className="pointer-events-none fixed inset-x-0 top-0 z-40 flex justify-center">
              <HeaderNav />
            </header>
            <main className="flex-1 pt-32 pb-24">{children}</main>
          </div>
        </LenisProvider>
      </body>
    </html>
  );
}
